export interface BuddhistCenter {
  id: string;
  rank: number;
  name: string;
  description: string;
  type: "monastery" | "meditation-center" | "temple" | "buddhist-center" | "retreat-center";
  location: string;
  country: string;
  image?: string;
  members: number;
  rating: number;
  status: "open" | "closed" | "retreat" | "by-appointment";
  featured: boolean;
  website?: string;
  phone?: string;
  email?: string;
  tags: string[];
  accentColor: string;
}

export const buddhistCenters: BuddhistCenter[] = [
  {
    id: "lang-mai",
    rank: 1,
    name: "Làng Mai (Plum Village)",
    description: "Tu viện Phật giáo Thiền phái Lâm Tế do Thiền sư Thích Nhất Hạnh sáng lập. Nơi thực hành chánh niệm và hòa bình nội tâm.",
    type: "monastery",
    location: "Dordogne",
    country: "Pháp",
    members: 15000,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://plumvillage.org",
    phone: "+33 5 53 58 48 58",
    email: "info@plumvillage.org",
    tags: ["Thiền", "Chánh niệm", "Thích Nhất Hạnh", "Tu tập"],
    accentColor: "#7bb89b",
  },
  {
    id: "thien-vien-truc-lam",
    rank: 2,
    name: "Thiền Viện Trúc Lâm",
    description: "Thiền viện tu tập theo truyền thống Thiền phái Trúc Lâm Yên Tử. Nơi thanh tịnh giữa núi rừng.",
    type: "meditation-center",
    location: "Đà Lạt",
    country: "Việt Nam",
    members: 8500,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://thienviendatlat.org",
    tags: ["Thiền", "Trúc Lâm", "Tu tập", "Núi rừng"],
    accentColor: "#8bc9a8",
  },
  {
    id: "chua-bao-quang",
    rank: 3,
    name: "Chùa Bảo Quang",
    description: "Ngôi chùa cổ kính với lịch sử hàng trăm năm. Trung tâm văn hóa Phật giáo quan trọng.",
    type: "monastery",
    location: "Thành phố Hồ Chí Minh",
    country: "Việt Nam",
    members: 12000,
    rating: 4.7,
    status: "open",
    featured: true,
    tags: ["Chùa cổ", "Văn hóa", "Lễ hội", "Cộng đồng"],
    accentColor: "#d4a574",
  },
  {
    id: "chua-linh-ung",
    rank: 4,
    name: "Chùa Linh Ứng",
    description: "Ngôi chùa nằm trên bán đảo Sơn Trà, nổi tiếng với tượng Phật Bà Quan Thế Âm cao nhất Việt Nam.",
    type: "temple",
    location: "Đà Nẵng",
    country: "Việt Nam",
    members: 6800,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://chualinhunga.vn",
    tags: ["Chùa", "Biển", "Du lịch", "Tâm linh"],
    accentColor: "#6ba3d4",
  },
  {
    id: "spirit-rock",
    rank: 5,
    name: "Spirit Rock Meditation Center",
    description: "Trung tâm thiền vipassana hàng đầu tại Mỹ. Giảng dạy thiền chánh niệm và tuệ giác.",
    type: "retreat-center",
    location: "California",
    country: "Hoa Kỳ",
    members: 5200,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://spiritrock.org",
    email: "info@spiritrock.org",
    tags: ["Vipassana", "Thiền", "Retreat", "Chánh niệm"],
    accentColor: "#c9a66b",
  },
  {
    id: "chua-ba-thien-hau",
    rank: 6,
    name: "Chùa Bà Thiên Hậu",
    description: "Ngôi chùa lâu đời nhất tại Sài Gòn, thờ Thiên Hậu Thánh Mẫu. Di tích văn hóa quốc gia.",
    type: "temple",
    location: "Thành phố Hồ Chí Minh",
    country: "Việt Nam",
    members: 9500,
    rating: 4.6,
    status: "open",
    featured: false,
    tags: ["Chùa cổ", "Di tích", "Thiên Hậu", "Lịch sử"],
    accentColor: "#d47b6b",
  },
  {
    id: "wat-pho",
    rank: 7,
    name: "Wat Pho (Chùa Phật Nằm)",
    description: "Ngôi chùa nổi tiếng với tượng Phật nằm dài 46m. Trung tâm y học cổ truyền Thái Lan.",
    type: "temple",
    location: "Bangkok",
    country: "Thái Lan",
    members: 11000,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://watpho.com",
    tags: ["Chùa", "Phật nằm", "Y học", "Du lịch"],
    accentColor: "#d4af37",
  },
  {
    id: "kopan-monastery",
    rank: 8,
    name: "Kopan Monastery",
    description: "Tu viện Phật giáo Tây Tạng tại Nepal. Trung tâm giảng dạy và tu tập thiền Phật giáo Tây Tạng.",
    type: "monastery",
    location: "Kathmandu",
    country: "Nepal",
    members: 4100,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "https://kopanmonastery.com",
    tags: ["Tây Tạng", "Thiền", "Retreat", "Nepal"],
    accentColor: "#9b7bb8",
  },
  {
    id: "thien-vien-vinh-nghiem",
    rank: 9,
    name: "Thiền Viện Vĩnh Nghiêm",
    description: "Thiền viện rộng lớn tại trung tâm Sài Gòn. Nơi tu tập và hoằng pháp cho cộng đồng đô thị.",
    type: "meditation-center",
    location: "Thành phố Hồ Chí Minh",
    country: "Việt Nam",
    members: 7800,
    rating: 4.5,
    status: "open",
    featured: false,
    tags: ["Thiền viện", "Đô thị", "Hoằng pháp", "Cộng đồng"],
    accentColor: "#8b9bb8",
  },
  {
    id: "insight-meditation-society",
    rank: 10,
    name: "Insight Meditation Society",
    description: "Trung tâm thiền vipassana uy tín tại Massachusetts. Tổ chức các khóa tu dài hạn và ngắn hạn.",
    type: "retreat-center",
    location: "Massachusetts",
    country: "Hoa Kỳ",
    members: 3900,
    rating: 4.8,
    status: "open",
    featured: false,
    website: "https://dharma.org",
    email: "rc@dharma.org",
    tags: ["Vipassana", "Retreat", "Thiền", "Tu tập"],
    accentColor: "#6b9bc9",
  },
  {
    id: "chua-mot-cot",
    rank: 11,
    name: "Chùa Một Cột",
    description: "Kiến trúc độc đáo với một cột trụ giữa hồ sen. Biểu tượng văn hóa của Hà Nội.",
    type: "temple",
    location: "Hà Nội",
    country: "Việt Nam",
    members: 5600,
    rating: 4.4,
    status: "open",
    featured: false,
    tags: ["Kiến trúc", "Di tích", "Hà Nội", "Văn hóa"],
    accentColor: "#b87b9b",
  },
  {
    id: "blue-cliff-monastery",
    rank: 12,
    name: "Blue Cliff Monastery",
    description: "Tu viện của Thiền sư Thích Nhất Hạnh tại New York. Thực hành chánh niệm theo truyền thống Làng Mai.",
    type: "monastery",
    location: "New York",
    country: "Hoa Kỳ",
    members: 3200,
    rating: 4.9,
    status: "retreat",
    featured: false,
    website: "https://bluecliffmonastery.org",
    tags: ["Làng Mai", "Chánh niệm", "Thích Nhất Hạnh", "Retreat"],
    accentColor: "#6b9bd4",
  },
];
